import { Zap, Home, Dumbbell, Dog, UtensilsCrossed, Baby, Car, Flower2, Shield, Shirt, Crown, LucideIcon } from "lucide-react";

export interface BrandCategory {
  id: string;
  label: string;
  icon: LucideIcon;
}

export interface BrandTimeline {
  month: string;
  event: string;
}

export interface BrandStrategy {
  title: string;
  description: string;
}

export interface TopBrand {
  rank: number;
  brand: string;
  category: string;
  logo: string;
  currentRanking: string;
  growth: string;
  achievement: string;
  yearAchieved: string;
  story: string;
  timeline: BrandTimeline[];
  strategies: BrandStrategy[];
  metrics: {
    monthlyRevenue: string;
    reviewCount: string;
    rating: string;
    returnRate: string;
  };
}

export const categories: BrandCategory[] = [
  { id: "all", label: "全部品类", icon: Crown },
  { id: "电子配件", label: "电子配件", icon: Zap },
  { id: "家居用品", label: "家居用品", icon: Home },
  { id: "健身器材", label: "健身器材", icon: Dumbbell },
  { id: "宠物用品", label: "宠物用品", icon: Dog },
  { id: "厨房用品", label: "厨房用品", icon: UtensilsCrossed },
  { id: "母婴用品", label: "母婴用品", icon: Baby },
  { id: "汽车配件", label: "汽车配件", icon: Car },
  { id: "园艺工具", label: "园艺工具", icon: Flower2 },
  { id: "安防设备", label: "安防设备", icon: Shield },
  { id: "时尚配饰", label: "时尚配饰", icon: Shirt },
];

const defaultTimeline: BrandTimeline[] = [
  { month: "第1月", event: "品牌诊断与市场调研" },
  { month: "第2月", event: "Listing优化与A+页面设计" },
  { month: "第3月", event: "广告策略制定与投放" },
  { month: "第4-6月", event: "销量爬升与排名提升" },
  { month: "第7-9月", event: "稳定Top 500排名" },
  { month: "第10-12月", event: "品牌影响力扩大" },
];

const defaultStrategies: BrandStrategy[] = [
  { title: "关键词优化", description: "深度挖掘高转化长尾词，优化标题和后台搜索词" },
  { title: "视觉升级", description: "专业产品摄影和A+页面设计，提升转化率30%+" },
  { title: "广告矩阵", description: "SP/SB/SD广告组合投放，精准触达目标客户" },
  { title: "评论管理", description: "合规获取真实评论，维护品牌口碑" },
];

export const topBrands: TopBrand[] = [
  // 电子配件 - 5个品牌
  {
    rank: 47,
    brand: "PowerTech",
    category: "电子配件",
    logo: "🔌",
    currentRanking: "Amazon 电子类 Top 50",
    growth: "+892%",
    achievement: "12个月内从新品牌进入前100",
    yearAchieved: "2024",
    story: "PowerTech是一家专注于快充技术的品牌。在与我们合作前，产品虽然质量过硬，但在Amazon上几乎没有曝光。通过系统化的品牌打造和精准的广告策略，我们帮助PowerTech在12个月内实现了从0到Top 50的飞跃。",
    timeline: [
      { month: "第1月", event: "品牌定位与竞品分析" },
      { month: "第2月", event: "产品Listing全面优化" },
      { month: "第3月", event: "启动Sponsored Products广告" },
      { month: "第5月", event: "销量突破月均5000单" },
      { month: "第8月", event: "获得Best Seller标签" },
      { month: "第12月", event: "稳定进入Top 50" },
    ],
    strategies: [
      { title: "技术差异化", description: "突出GaN快充技术优势，与竞品形成差异化竞争" },
      { title: "视频营销", description: "制作产品演示视频，展示快充效果" },
      { title: "捆绑销售", description: "设计多件套装，提升客单价" },
      { title: "季节促销", description: "把握Prime Day和黑五节点，单日销量破万" },
    ],
    metrics: { monthlyRevenue: "$580K", reviewCount: "15,000+", rating: "4.7", returnRate: "2.1%" },
  },
  {
    rank: 78,
    brand: "ChargeMax",
    category: "电子配件",
    logo: "🔋",
    currentRanking: "Amazon 电子类 Top 80",
    growth: "+756%",
    achievement: "充电器品类销量第一",
    yearAchieved: "2024",
    story: "ChargeMax专注于移动电源市场。通过精准的市场定位和高效的供应链管理，我们帮助品牌在激烈的竞争中脱颖而出，成为充电器品类的销量冠军。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$420K", reviewCount: "12,000+", rating: "4.6", returnRate: "2.5%" },
  },
  {
    rank: 112,
    brand: "TechLink",
    category: "电子配件",
    logo: "📱",
    currentRanking: "Amazon 电子类 Top 120",
    growth: "+623%",
    achievement: "手机配件Best Seller",
    yearAchieved: "2023",
    story: "TechLink从一个小型手机配件供应商成长为Amazon手机配件类目的Best Seller。我们的策略是聚焦细分市场，打造爆款单品。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$350K", reviewCount: "8,500+", rating: "4.5", returnRate: "3.0%" },
  },
  {
    rank: 156,
    brand: "SmartHub",
    category: "电子配件",
    logo: "🎧",
    currentRanking: "Amazon 电子类 Top 160",
    growth: "+534%",
    achievement: "Prime Day 销量Top 20",
    yearAchieved: "2024",
    story: "SmartHub专注于智能家居配件。通过Prime Day的爆发式营销，品牌一举进入电子类Top 160。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$280K", reviewCount: "6,200+", rating: "4.6", returnRate: "2.8%" },
  },
  {
    rank: 203,
    brand: "WirelessPro",
    category: "电子配件",
    logo: "📡",
    currentRanking: "Amazon 电子类 Top 210",
    growth: "+445%",
    achievement: "无线设备类目增长最快",
    yearAchieved: "2023",
    story: "WirelessPro抓住了无线充电的风口，成为类目增长最快的品牌之一。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$220K", reviewCount: "4,800+", rating: "4.4", returnRate: "3.2%" },
  },

  // 家居用品 - 5个品牌
  {
    rank: 89,
    brand: "HomeComfort",
    category: "家居用品",
    logo: "🏠",
    currentRanking: "Amazon 家居类 Top 100",
    growth: "+654%",
    achievement: "季度销售额突破$2M",
    yearAchieved: "2024",
    story: "HomeComfort是一个专注于舒适家居产品的品牌。通过精准的产品定位和卓越的客户服务，我们帮助品牌在短短一年内实现季度销售额突破$2M的里程碑。",
    timeline: [
      { month: "第1月", event: "产品线梳理与定价策略" },
      { month: "第2月", event: "主图和A+页面升级" },
      { month: "第3-4月", event: "社交媒体联动营销" },
      { month: "第5-8月", event: "销量稳步增长" },
      { month: "第9-12月", event: "季度销售额突破$2M" },
    ],
    strategies: [
      { title: "场景营销", description: "打造温馨家居场景，提升品牌调性" },
      { title: "口碑传播", description: "鼓励用户分享使用体验，形成自然传播" },
      { title: "产品组合", description: "设计家居套装，满足一站式购买需求" },
      { title: "季节策略", description: "针对不同季节推出主题产品" },
    ],
    metrics: { monthlyRevenue: "$680K", reviewCount: "18,000+", rating: "4.8", returnRate: "1.8%" },
  },
  {
    rank: 134,
    brand: "CozyLiving",
    category: "家居用品",
    logo: "🛋️",
    currentRanking: "Amazon 家居类 Top 140",
    growth: "+578%",
    achievement: "软装品类Top 10",
    yearAchieved: "2024",
    story: "CozyLiving专注于沙发配件和软装产品，通过独特的设计理念成为软装品类的佼佼者。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$450K", reviewCount: "11,000+", rating: "4.7", returnRate: "2.2%" },
  },
  {
    rank: 189,
    brand: "CleanHome",
    category: "家居用品",
    logo: "🧹",
    currentRanking: "Amazon 家居类 Top 200",
    growth: "+489%",
    achievement: "清洁用品Best Seller",
    yearAchieved: "2023",
    story: "CleanHome凭借创新的清洁工具设计，成为家居清洁品类的Best Seller。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$320K", reviewCount: "9,500+", rating: "4.6", returnRate: "2.5%" },
  },
  {
    rank: 245,
    brand: "StoragePlus",
    category: "家居用品",
    logo: "📦",
    currentRanking: "Amazon 家居类 Top 250",
    growth: "+412%",
    achievement: "收纳品类销量冠军",
    yearAchieved: "2023",
    story: "StoragePlus专注于家居收纳解决方案，帮助用户打造整洁有序的生活空间。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$260K", reviewCount: "7,200+", rating: "4.5", returnRate: "2.8%" },
  },
  {
    rank: 312,
    brand: "LightDecor",
    category: "家居用品",
    logo: "💡",
    currentRanking: "Amazon 家居类 Top 320",
    growth: "+367%",
    achievement: "灯饰品类月销$500K",
    yearAchieved: "2024",
    story: "LightDecor以创意灯饰设计著称，为家居空间增添独特的氛围感。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$500K", reviewCount: "5,800+", rating: "4.6", returnRate: "3.0%" },
  },

  // 健身器材 - 5个品牌
  {
    rank: 123,
    brand: "FitPro Elite",
    category: "健身器材",
    logo: "💪",
    currentRanking: "Amazon 运动类 Top 150",
    growth: "+478%",
    achievement: "Best Seller 标签保持180天",
    yearAchieved: "2024",
    story: "FitPro Elite是一个专业健身器材品牌。我们帮助品牌建立了强大的社群营销体系，Best Seller标签已持续保持180天以上。",
    timeline: [
      { month: "第1月", event: "健身社群调研与KOL合作" },
      { month: "第2月", event: "产品视频和教程制作" },
      { month: "第3月", event: "启动影响者营销计划" },
      { month: "第4-6月", event: "社群口碑快速传播" },
      { month: "第7月", event: "获得Best Seller标签" },
      { month: "第8-12月", event: "持续保持Best Seller" },
    ],
    strategies: [
      { title: "社群营销", description: "建立健身爱好者社群，形成口碑传播" },
      { title: "KOL合作", description: "与健身博主合作，扩大品牌影响力" },
      { title: "教程内容", description: "制作使用教程视频，提升产品价值" },
      { title: "会员体系", description: "建立品牌会员体系，提升复购率" },
    ],
    metrics: { monthlyRevenue: "$520K", reviewCount: "14,000+", rating: "4.8", returnRate: "1.5%" },
  },
  {
    rank: 167,
    brand: "GymMaster",
    category: "健身器材",
    logo: "🏋️",
    currentRanking: "Amazon 运动类 Top 180",
    growth: "+534%",
    achievement: "力量训练器材Top 5",
    yearAchieved: "2024",
    story: "GymMaster专注于力量训练器材，以专业级品质赢得了健身爱好者的青睐。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$380K", reviewCount: "8,800+", rating: "4.7", returnRate: "2.0%" },
  },
  {
    rank: 198,
    brand: "YogaZen",
    category: "健身器材",
    logo: "🧘",
    currentRanking: "Amazon 运动类 Top 200",
    growth: "+423%",
    achievement: "瑜伽用品Best Seller",
    yearAchieved: "2023",
    story: "YogaZen以环保材质和舒适设计著称，成为瑜伽爱好者的首选品牌。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$290K", reviewCount: "10,500+", rating: "4.8", returnRate: "1.8%" },
  },
  {
    rank: 267,
    brand: "CardioMax",
    category: "健身器材",
    logo: "🏃",
    currentRanking: "Amazon 运动类 Top 280",
    growth: "+389%",
    achievement: "有氧器材类目第一",
    yearAchieved: "2023",
    story: "CardioMax专注于家用有氧器材，帮助用户在家实现专业级健身体验。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$340K", reviewCount: "6,500+", rating: "4.5", returnRate: "2.5%" },
  },
  {
    rank: 345,
    brand: "FlexBand",
    category: "健身器材",
    logo: "🎽",
    currentRanking: "Amazon 运动类 Top 350",
    growth: "+356%",
    achievement: "弹力带销量破100万件",
    yearAchieved: "2024",
    story: "FlexBand以高性价比的弹力带产品切入市场，累计销量已突破100万件。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$180K", reviewCount: "22,000+", rating: "4.6", returnRate: "2.2%" },
  },

  // 宠物用品 - 5个品牌
  {
    rank: 156,
    brand: "PetLove Premium",
    category: "宠物用品",
    logo: "🐕",
    currentRanking: "Amazon 宠物类 Top 200",
    growth: "+567%",
    achievement: "复购率达到45%",
    yearAchieved: "2023",
    story: "PetLove Premium专注于高端宠物用品。通过建立强大的品牌忠诚度，我们帮助品牌实现了45%的超高复购率。",
    timeline: [
      { month: "第1月", event: "宠物主人调研与需求分析" },
      { month: "第2月", event: "产品包装和品牌升级" },
      { month: "第3月", event: "订阅制会员计划上线" },
      { month: "第4-6月", event: "口碑传播与社群建设" },
      { month: "第7-12月", event: "复购率稳定在45%以上" },
    ],
    strategies: [
      { title: "订阅服务", description: "推出宠物用品订阅计划，提升客户黏性" },
      { title: "社群运营", description: "建立宠物主人社群，分享养宠经验" },
      { title: "品质保证", description: "严格品控，建立高端品牌形象" },
      { title: "情感营销", description: "讲述宠物故事，引发情感共鸣" },
    ],
    metrics: { monthlyRevenue: "$420K", reviewCount: "13,000+", rating: "4.9", returnRate: "1.2%" },
  },
  {
    rank: 189,
    brand: "PawCare",
    category: "宠物用品",
    logo: "🐾",
    currentRanking: "Amazon 宠物类 Top 200",
    growth: "+512%",
    achievement: "宠物护理类Best Seller",
    yearAchieved: "2024",
    story: "PawCare专注于宠物护理产品，以专业配方赢得了宠物主人的信任。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$350K", reviewCount: "9,200+", rating: "4.7", returnRate: "1.8%" },
  },
  {
    rank: 234,
    brand: "CatKingdom",
    category: "宠物用品",
    logo: "🐱",
    currentRanking: "Amazon 宠物类 Top 250",
    growth: "+445%",
    achievement: "猫用品类目Top 10",
    yearAchieved: "2024",
    story: "CatKingdom专注于猫咪用品市场，以创意设计深受猫奴喜爱。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$280K", reviewCount: "7,500+", rating: "4.6", returnRate: "2.0%" },
  },
  {
    rank: 298,
    brand: "PetToys",
    category: "宠物用品",
    logo: "🦴",
    currentRanking: "Amazon 宠物类 Top 300",
    growth: "+398%",
    achievement: "宠物玩具月销$300K",
    yearAchieved: "2023",
    story: "PetToys以创新的宠物玩具设计著称，让宠物玩乐更加有趣。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$300K", reviewCount: "11,000+", rating: "4.5", returnRate: "2.5%" },
  },
  {
    rank: 367,
    brand: "AquaPet",
    category: "宠物用品",
    logo: "🐠",
    currentRanking: "Amazon 宠物类 Top 380",
    growth: "+334%",
    achievement: "水族用品增长第一",
    yearAchieved: "2024",
    story: "AquaPet专注于水族用品市场，为鱼类爱好者提供专业解决方案。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$180K", reviewCount: "4,200+", rating: "4.6", returnRate: "2.8%" },
  },

  // 厨房用品 - 5个品牌
  {
    rank: 145,
    brand: "ChefPro",
    category: "厨房用品",
    logo: "👨‍🍳",
    currentRanking: "Amazon 厨房类 Top 150",
    growth: "+612%",
    achievement: "厨具套装Best Seller",
    yearAchieved: "2024",
    story: "ChefPro以专业级厨具著称，帮助家庭厨师实现专业烹饪体验。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$480K", reviewCount: "16,000+", rating: "4.8", returnRate: "1.5%" },
  },
  {
    rank: 198,
    brand: "KitchenMaster",
    category: "厨房用品",
    logo: "🍳",
    currentRanking: "Amazon 厨房类 Top 200",
    growth: "+723%",
    achievement: "Prime Day 销量Top 10",
    yearAchieved: "2023",
    story: "KitchenMaster是一个综合厨房用品品牌。在Prime Day期间，我们帮助品牌创造了单日销量Top 10的佳绩。",
    timeline: [
      { month: "第1月", event: "Prime Day策略制定" },
      { month: "第2月", event: "库存准备与物流优化" },
      { month: "第3月", event: "预热活动与会员促销" },
      { month: "Prime Day", event: "单日销量突破Top 10" },
      { month: "第5-12月", event: "持续保持高销量" },
    ],
    strategies: [
      { title: "大促策略", description: "精心策划Prime Day营销方案" },
      { title: "库存管理", description: "提前备货，确保大促期间不断货" },
      { title: "价格策略", description: "设计阶梯式折扣，最大化转化" },
      { title: "广告加码", description: "大促期间加大广告投入" },
    ],
    metrics: { monthlyRevenue: "$550K", reviewCount: "19,000+", rating: "4.7", returnRate: "2.0%" },
  },
  {
    rank: 223,
    brand: "BlendMax",
    category: "厨房用品",
    logo: "🥤",
    currentRanking: "Amazon 厨房类 Top 230",
    growth: "+534%",
    achievement: "搅拌机类目销量第一",
    yearAchieved: "2024",
    story: "BlendMax专注于搅拌机市场，以强劲性能和时尚外观赢得市场。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$380K", reviewCount: "8,500+", rating: "4.6", returnRate: "2.2%" },
  },
  {
    rank: 278,
    brand: "CookWare",
    category: "厨房用品",
    logo: "🥘",
    currentRanking: "Amazon 厨房类 Top 280",
    growth: "+467%",
    achievement: "不粘锅系列月销$400K",
    yearAchieved: "2023",
    story: "CookWare以高品质不粘锅著称，为用户提供健康烹饪体验。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$400K", reviewCount: "12,000+", rating: "4.7", returnRate: "1.8%" },
  },
  {
    rank: 334,
    brand: "KnifeEdge",
    category: "厨房用品",
    logo: "🔪",
    currentRanking: "Amazon 厨房类 Top 340",
    growth: "+389%",
    achievement: "刀具套装5星好评2万+",
    yearAchieved: "2024",
    story: "KnifeEdge专注于专业刀具，以卓越的锋利度和耐用性著称。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$260K", reviewCount: "20,000+", rating: "4.9", returnRate: "1.2%" },
  },

  // 母婴用品 - 5个品牌
  {
    rank: 167,
    brand: "MomCare",
    category: "母婴用品",
    logo: "🍼",
    currentRanking: "Amazon 母婴类 Top 180",
    growth: "+534%",
    achievement: "婴儿奶瓶类Best Seller",
    yearAchieved: "2024",
    story: "MomCare专注于婴儿喂养产品，以安全材质和人性化设计赢得新手妈妈的信赖。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$420K", reviewCount: "15,000+", rating: "4.8", returnRate: "1.5%" },
  },
  {
    rank: 212,
    brand: "TinySteps",
    category: "母婴用品",
    logo: "👣",
    currentRanking: "Amazon 母婴类 Top 220",
    growth: "+478%",
    achievement: "婴儿用品月销$600K",
    yearAchieved: "2024",
    story: "TinySteps陪伴宝宝成长的每一步，从爬行到行走，提供全方位的产品支持。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$600K", reviewCount: "11,000+", rating: "4.7", returnRate: "1.8%" },
  },
  {
    rank: 234,
    brand: "BabyJoy",
    category: "母婴用品",
    logo: "👶",
    currentRanking: "Amazon 母婴类 Top 250",
    growth: "+412%",
    achievement: "Amazon's Choice 认证",
    yearAchieved: "2023",
    story: "BabyJoy致力于为宝宝创造快乐童年，产品获得Amazon's Choice认证。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$350K", reviewCount: "8,800+", rating: "4.6", returnRate: "2.0%" },
  },
  {
    rank: 289,
    brand: "SafeBaby",
    category: "母婴用品",
    logo: "🛡️",
    currentRanking: "Amazon 母婴类 Top 300",
    growth: "+398%",
    achievement: "安全座椅类目Top 5",
    yearAchieved: "2023",
    story: "SafeBaby专注于婴儿安全产品，以严格的安全标准保护每一个宝宝。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$480K", reviewCount: "6,500+", rating: "4.9", returnRate: "0.8%" },
  },
  {
    rank: 356,
    brand: "PlayTime",
    category: "母婴用品",
    logo: "🧸",
    currentRanking: "Amazon 母婴类 Top 360",
    growth: "+345%",
    achievement: "益智玩具Best Seller",
    yearAchieved: "2024",
    story: "PlayTime以寓教于乐的益智玩具著称，帮助宝宝在玩乐中成长。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$220K", reviewCount: "9,200+", rating: "4.7", returnRate: "2.2%" },
  },

  // 汽车配件 - 5个品牌
  {
    rank: 178,
    brand: "CarShine",
    category: "汽车配件",
    logo: "✨",
    currentRanking: "Amazon 汽车类 Top 180",
    growth: "+623%",
    achievement: "汽车美容类Best Seller",
    yearAchieved: "2024",
    story: "CarShine专注于汽车美容产品，让每一辆车都能焕发光彩。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$380K", reviewCount: "14,000+", rating: "4.7", returnRate: "1.8%" },
  },
  {
    rank: 234,
    brand: "DriveMax",
    category: "汽车配件",
    logo: "🔧",
    currentRanking: "Amazon 汽车类 Top 240",
    growth: "+489%",
    achievement: "工具套装月销$350K",
    yearAchieved: "2024",
    story: "DriveMax为车主提供专业级汽车维修工具，让DIY保养更加简单。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$350K", reviewCount: "8,500+", rating: "4.6", returnRate: "2.0%" },
  },
  {
    rank: 287,
    brand: "AutoCare Pro",
    category: "汽车配件",
    logo: "🚗",
    currentRanking: "Amazon 汽车类 Top 300",
    growth: "+534%",
    achievement: "4.8星平均评分，2万+评论",
    yearAchieved: "2023",
    story: "AutoCare Pro是一个综合汽车配件品牌。凭借优质的产品和服务，我们帮助品牌积累了2万+好评，平均评分达到4.8星。",
    timeline: [
      { month: "第1月", event: "产品质量优化" },
      { month: "第2月", event: "客服体系升级" },
      { month: "第3-6月", event: "好评积累与口碑传播" },
      { month: "第7-12月", event: "评论突破2万+" },
    ],
    strategies: [
      { title: "品质第一", description: "严格品控，确保每件产品都达到高标准" },
      { title: "售后服务", description: "建立完善的售后体系，快速响应客户需求" },
      { title: "评论引导", description: "合规引导好评，建立品牌口碑" },
      { title: "问题处理", description: "及时处理负评，化解客户不满" },
    ],
    metrics: { monthlyRevenue: "$420K", reviewCount: "20,000+", rating: "4.8", returnRate: "1.5%" },
  },
  {
    rank: 312,
    brand: "AutoLight",
    category: "汽车配件",
    logo: "💡",
    currentRanking: "Amazon 汽车类 Top 320",
    growth: "+412%",
    achievement: "LED车灯销量冠军",
    yearAchieved: "2023",
    story: "AutoLight专注于LED汽车照明，以高亮度和长寿命著称。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$280K", reviewCount: "11,000+", rating: "4.6", returnRate: "2.2%" },
  },
  {
    rank: 389,
    brand: "CarTech",
    category: "汽车配件",
    logo: "📻",
    currentRanking: "Amazon 汽车类 Top 400",
    growth: "+356%",
    achievement: "车载电子类增长第一",
    yearAchieved: "2024",
    story: "CarTech专注于车载电子产品，让驾驶体验更加智能便捷。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$220K", reviewCount: "6,800+", rating: "4.5", returnRate: "2.5%" },
  },

  // 园艺工具 - 4个品牌
  {
    rank: 234,
    brand: "GreenThumb",
    category: "园艺工具",
    logo: "🌿",
    currentRanking: "Amazon 园艺类 Top 250",
    growth: "+512%",
    achievement: "园艺工具套装Best Seller",
    yearAchieved: "2024",
    story: "GreenThumb为园艺爱好者提供专业工具套装，让园艺工作更加轻松高效。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$320K", reviewCount: "9,500+", rating: "4.7", returnRate: "1.8%" },
  },
  {
    rank: 289,
    brand: "PlantCare",
    category: "园艺工具",
    logo: "🪴",
    currentRanking: "Amazon 园艺类 Top 300",
    growth: "+445%",
    achievement: "花盆花器月销$200K",
    yearAchieved: "2023",
    story: "PlantCare以创意花盆设计著称，为植物打造美丽的家。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$200K", reviewCount: "7,200+", rating: "4.6", returnRate: "2.5%" },
  },
  {
    rank: 356,
    brand: "GardenGlow",
    category: "园艺工具",
    logo: "🌱",
    currentRanking: "Amazon 园艺类 Top 400",
    growth: "+389%",
    achievement: "春季销售季Top卖家",
    yearAchieved: "2024",
    story: "GardenGlow在春季园艺旺季表现突出，成为季节性销售的Top卖家。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$280K", reviewCount: "5,800+", rating: "4.5", returnRate: "2.8%" },
  },
  {
    rank: 412,
    brand: "LawnMaster",
    category: "园艺工具",
    logo: "🌻",
    currentRanking: "Amazon 园艺类 Top 420",
    growth: "+334%",
    achievement: "草坪护理类目Top 10",
    yearAchieved: "2024",
    story: "LawnMaster专注于草坪护理工具，帮助用户打造完美的草坪。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$180K", reviewCount: "4,500+", rating: "4.6", returnRate: "2.2%" },
  },

  // 安防设备 - 4个品牌
  {
    rank: 198,
    brand: "SecureHome",
    category: "安防设备",
    logo: "🏠",
    currentRanking: "Amazon 安防类 Top 200",
    growth: "+578%",
    achievement: "智能门锁Best Seller",
    yearAchieved: "2024",
    story: "SecureHome专注于智能家居安防，以便捷安全的智能门锁赢得市场。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$450K", reviewCount: "12,000+", rating: "4.7", returnRate: "1.5%" },
  },
  {
    rank: 267,
    brand: "WatchGuard",
    category: "安防设备",
    logo: "📹",
    currentRanking: "Amazon 安防类 Top 280",
    growth: "+489%",
    achievement: "监控摄像头月销$450K",
    yearAchieved: "2023",
    story: "WatchGuard提供专业级监控解决方案，守护家庭和企业安全。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$450K", reviewCount: "8,500+", rating: "4.6", returnRate: "2.0%" },
  },
  {
    rank: 345,
    brand: "AlertPro",
    category: "安防设备",
    logo: "🚨",
    currentRanking: "Amazon 安防类 Top 350",
    growth: "+398%",
    achievement: "报警系统类目第一",
    yearAchieved: "2024",
    story: "AlertPro专注于智能报警系统，提供全方位的安全预警服务。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$280K", reviewCount: "5,200+", rating: "4.7", returnRate: "1.8%" },
  },
  {
    rank: 412,
    brand: "TechSafe",
    category: "安防设备",
    logo: "🔒",
    currentRanking: "Amazon 安防类 Top 450",
    growth: "+445%",
    achievement: "B2B订单增长300%",
    yearAchieved: "2024",
    story: "TechSafe是一个专业安防品牌。通过拓展B2B渠道，我们帮助品牌实现了企业订单300%的增长。",
    timeline: [
      { month: "第1月", event: "B2B市场调研" },
      { month: "第2月", event: "企业客户开发策略" },
      { month: "第3-6月", event: "建立企业销售渠道" },
      { month: "第7-12月", event: "B2B订单增长300%" },
    ],
    strategies: [
      { title: "B2B开发", description: "建立专门的企业客户开发团队" },
      { title: "批量定价", description: "设计有竞争力的批量采购价格" },
      { title: "定制服务", description: "提供企业定制安防方案" },
      { title: "长期合作", description: "建立企业客户长期合作关系" },
    ],
    metrics: { monthlyRevenue: "$380K", reviewCount: "3,800+", rating: "4.8", returnRate: "1.2%" },
  },

  // 时尚配饰 - 4个品牌
  {
    rank: 178,
    brand: "TrendyBags",
    category: "时尚配饰",
    logo: "🎒",
    currentRanking: "Amazon 时尚类 Top 180",
    growth: "+612%",
    achievement: "背包类目Best Seller",
    yearAchieved: "2024",
    story: "TrendyBags以时尚与实用并重的背包设计，成为年轻人的时尚选择。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$420K", reviewCount: "15,000+", rating: "4.7", returnRate: "2.0%" },
  },
  {
    rank: 256,
    brand: "ShineJewels",
    category: "时尚配饰",
    logo: "💎",
    currentRanking: "Amazon 时尚类 Top 260",
    growth: "+523%",
    achievement: "首饰类月销$800K",
    yearAchieved: "2024",
    story: "ShineJewels以精致的首饰设计著称，让每位女性都能闪耀自信。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$800K", reviewCount: "18,000+", rating: "4.6", returnRate: "3.0%" },
  },
  {
    rank: 334,
    brand: "SunStyle",
    category: "时尚配饰",
    logo: "🕶️",
    currentRanking: "Amazon 时尚类 Top 340",
    growth: "+445%",
    achievement: "太阳镜夏季销量冠军",
    yearAchieved: "2023",
    story: "SunStyle专注于时尚太阳镜，在夏季销售旺季表现出色。",
    timeline: defaultTimeline,
    strategies: defaultStrategies,
    metrics: { monthlyRevenue: "$350K", reviewCount: "12,000+", rating: "4.5", returnRate: "2.5%" },
  },
  {
    rank: 489,
    brand: "StyleWear",
    category: "时尚配饰",
    logo: "👜",
    currentRanking: "Amazon 时尚类 Top 500",
    growth: "+367%",
    achievement: "品牌搜索量增长500%",
    yearAchieved: "2023",
    story: "StyleWear是一个新兴时尚配饰品牌。通过品牌建设和社交媒体营销，我们帮助品牌搜索量增长了500%。",
    timeline: [
      { month: "第1月", event: "品牌定位与视觉升级" },
      { month: "第2月", event: "社交媒体矩阵搭建" },
      { month: "第3-6月", event: "网红合作与内容营销" },
      { month: "第7-12月", event: "品牌搜索量增长500%" },
    ],
    strategies: [
      { title: "品牌建设", description: "打造独特的品牌视觉识别系统" },
      { title: "社媒营销", description: "在Instagram和TikTok建立品牌影响力" },
      { title: "网红合作", description: "与时尚博主合作推广" },
      { title: "内容创作", description: "制作时尚穿搭内容，引发用户互动" },
    ],
    metrics: { monthlyRevenue: "$280K", reviewCount: "8,500+", rating: "4.6", returnRate: "2.8%" },
  },
];
